[package]
name = "day_13"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.95"
aoc_utils = { version = "0.1.0", path = "../aoc_utils" }
pathfinding = "4.12.0"
regex = "1.11.1"
thiserror = "2.0.9"
